service: preview4-simple-tc-enabled-qj-disabled

provider:
  name: aws
  runtime: provided
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - xray:PutTraceSegments
       - xray:PutTelemetryRecords
      Resource: "*"



package:
  individually: true

functions:
  handle:
    handler: bootstrap
    package:
      artifact: bin/release/netcoreapp3.0/simple-tc-enabled-qj-disabled.zip
