service: preview4-complex-tc-disabled

provider:
  name: aws
  runtime: provided
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "*"
      Resource: "*"



package:
  individually: true

functions:
  handle:
    handler: bootstrap
    package:
      artifact: bin/release/netcoreapp3.0/complex-tc-disabled.zip
